.echo "Loaded from:"
.echo "$$>a<${$arg0}"
bc *
bp condrv!CdpFastIoDeviceControl ".echo \"setting breakpoint chain on condrv!CdpFastIoDeviceControl, do a `bl` to check how i did it\";.echo \"bp 0\";!process -1 0;!thread; bd 0; bp nt!MmCreateProcessAddressSpace \"bd 1;.echo \\\"bp 1\\\";!thread;g\"; g"


* bp condrv!CdpFastIoDeviceControl ".echo \"bp 0\";!process -1; !thread; bd 0; g"
* bp nt!MmCreateProcessAddressSpace "bd 1;.echo \"bp 1\";!thread;g"




* this will crash my debugger, rdp will not come online in time for my liking. But it is working:
* bp condrv!CdpFastIoDeviceControl "!process -1 0;g"
* bp condrv!CdpFastIoDeviceControl "!thread;g"

* bp condrv!CdpFastIoDeviceControl "g"
* $$>a<\\tsclient\_home_deadbeef_github_win-kernel-d\course-sysinternals\Part-01\debugging-scripts.wsd


